await cdp('Network.enable');await cdp('Network.setCacheDisabled',{cacheDisabled:true});await cdp('Network.setBlockedURLs',{urls:['*fonts.googleapis.com*','*fonts.gstatic.com*']});
const delay=async()=>{await new Promise(r=>setTimeout(r,600));for(let n=0;n<80;n++){const r=await ev('document.body.classList.contains("buyer-app")&&!document.querySelector("#main").innerText.includes("Đang tải")&&!document.querySelector("#main").innerText.includes("Đang xử lý thanh toán demo")');if(r.value)return;await new Promise(r=>setTimeout(r,150));}throw Error('Page did not finish loading')};
const E=async x=>{const r=await ev(x);if(r.subtype==='error')throw Error(r.description);return r.value;};
const check=async(label,x)=>{if(!await E(x))throw Error('FAIL '+label+' '+await E('document.body.innerText.slice(-1200)'));console.log('PASS',label)};
const fill=async(name,data)=>{await E('(()=>{const f=document.querySelector('+JSON.stringify('form[data-form="'+name+'"]')+');if(!f)throw Error("Missing form '+name+'");for(const [k,v] of Object.entries('+JSON.stringify(data)+')){const el=f.elements[k];if(!el)throw Error("Missing "+k);if(el.type==="checkbox")el.checked=v;else el.value=v;el.dispatchEvent(new Event("input",{bubbles:true}));}f.requestSubmit();})()');await delay();};
const click=async(action,id)=>{await E('document.querySelector('+JSON.stringify('[data-action="'+action+'"]'+(id?'[data-id="'+id+'"]':''))+').click()');await delay();};
const confirm=async()=>{await E('document.querySelector("#confirm button[value=ok]").click()');await delay();};
const state=async()=>JSON.parse(await E('localStorage.getItem("pcmatch-demo-v2")'));
await nav('buyer/home.html');await delay();await E('localStorage.clear();sessionStorage.clear()');await nav('auth/login.html?mode=register');await delay();await fill('register',{name:'Người mua A',email:'after-a@test.local',password:'Demo12345',confirm:'Demo12345'});
await fill('profile',{name:'Hồ sơ riêng A',phone:'0901234567'});await check('profile updated for own id','document.body.innerText.includes("Hồ sơ riêng A")');await E('document.querySelector("[name=name]").value="Không lưu"');await click('account-cancel');await check('cancel profile restores value','document.querySelector("[name=name]").value==="Hồ sơ riêng A"');await fill('password-change',{old:'Wrong1234',password:'Changed123',confirm:'Changed123'});await check('bad old password rejected','!!document.querySelector("[name=old][aria-invalid=true]")');await fill('password-change',{old:'Demo12345',password:'Changed123',confirm:'Changed123'});
await nav('buyer/model.html?id=CPU-7600');await delay();await fill('offer',{qty:2,target:'cart'});await nav('buyer/model.html?id=SSD-SN770');await delay();await fill('offer',{qty:1,target:'cart'});await nav('buyer/model.html?id=PSU-750&shop=TZ');await delay();await fill('offer',{qty:1,target:'cart'});await nav('buyer/addresses.html?checkout=1');await delay();await fill('address',{name:'Người mua A',phone:'0901234567',detail:'123 Đường Mẫu, Phường Demo',region:'HCM'});await fill('voucher',{code:'PC100'});await fill('place-order',{changes:true,terms:true});await fill('pay',{result:'paid'});
let st=await state(),order=st.orders[0],bp=order.suborders.find(s=>s.shopId==='BP'),tz=order.suborders.find(s=>s.shopId==='TZ');const orderPath='buyer/order.html?id='+order.id;await nav(orderPath);await delay();await click('cancel-order',tz.id);await E('document.querySelector("#confirm [name=reason]").value="Đổi kế hoạch mua"');await confirm();await check('cancellation pending independent','JSON.parse(localStorage.getItem("pcmatch-demo-v2")).orders[0].suborders.find(s=>s.shopId==="BP").status==="Chờ shop xác nhận"');await click('cancel-reject',tz.id);await check('rejected cancellation with reason','document.body.innerText.includes("Yêu cầu hủy: Từ chối")&&document.body.innerText.includes("Shop đã chuẩn bị hàng")');await click('cancel-order',tz.id);await E('document.querySelector("#confirm [name=reason]").value="Không còn nhu cầu"');await confirm();await click('cancel-approve',tz.id);await check('approved cancel does not mean refunded','document.body.innerText.includes("Được duyệt")&&document.body.innerText.includes("Đang xử lý")');
await click('order-confirm',bp.id);await click('order-ship',bp.id);await click('order-failed',bp.id);await check('failed delivery creates no refund','!JSON.parse(localStorage.getItem("pcmatch-demo-v2")).orders[0].suborders.find(s=>s.shopId==="BP").refund');const cpu=bp.items.find(i=>i.modelId==='CPU-7600'),ssd=bp.items.find(i=>i.modelId==='SSD-SN770');await nav('buyer/cases.html?new=review&order='+order.id+'&sub='+bp.id+'&item='+cpu.id);await delay();await check('review before delivery blocked','!document.querySelector("form[data-form=review]")');await nav(orderPath);await delay();await click('order-ship',bp.id);await click('order-delivered',bp.id);
const itemPath=i=>'buyer/cases.html?new=aftersale&order='+order.id+'&sub='+bp.id+'&item='+i.id;
await nav(itemPath(cpu));await delay();await fill('case',{type:'return',qty:2,reason:'Lỗi demo',text:'Xin kiểm tra và hoàn khoản đã trả.'});await check('quantity serial mismatch blocked','document.body.innerText.includes("Chọn serial đúng số lượng")');
await E(`(()=>{const f=document.querySelector('form[data-form=case]');const dt=new DataTransfer();dt.items.add(new File(['bad'],'bad.txt',{type:'text/plain'}));f.elements.evidence.files=dt.files;})()`);await fill('case',{qty:1});await check('invalid evidence rejected with text kept','document.body.innerText.includes("Chỉ nhận PNG/JPEG/PDF")&&document.querySelector("[name=text]").value.includes("Xin kiểm tra")');await E(`(()=>{const f=document.querySelector('form[data-form=case]');const dt=new DataTransfer();dt.items.add(new File(['%PDF-1.4 demo'],'proof.pdf',{type:'application/pdf'}));f.elements.evidence.files=dt.files;})()`);await fill('case',{});st=await state();let ret=st.cases[0];await check('return case keeps serial evidence policy','document.body.innerText.includes("proof.pdf")&&JSON.parse(localStorage.getItem("pcmatch-demo-v2")).cases[0].serials.length===1');await click('case-more',ret.id);await fill('case-message',{text:'Bổ sung mô tả lỗi khi khởi động.'});await click('case-inspect',ret.id);await click('case-sent',ret.id);await click('case-refund',ret.id);await nav(orderPath);await delay();await check('refund explains financial amounts','document.body.innerText.includes("Đề nghị:")&&document.body.innerText.includes("Được duyệt:")&&document.body.innerText.includes("Đã hoàn:")');st=await state();let refund=st.orders[0].suborders.find(s=>s.shopId==='BP').refund;await click('refund-fail',refund.id);await check('refund failure retry visible','document.body.innerText.includes("Thất bại — cần xử lý lại")');await click('refund-done',refund.id);
await nav(itemPath(cpu));await delay();await fill('case',{type:'return',qty:1,reason:'Lặp serial',text:'Không được trả cùng serial lần nữa.'});await check('duplicate returned serial blocked','document.body.innerText.includes("Serial đã có hồ sơ")');
await nav(itemPath(cpu));await delay();await E(`document.querySelector('[name=serials]').value=`+JSON.stringify(cpu.serials[1]));await fill('case',{type:'return',qty:1,reason:'Trả serial còn lại',text:'Kiểm tra món thứ hai độc lập với lần trả trước.'});let secondReturn=(await state()).cases.find(c=>c.type==='return'&&c.id!==ret.id);await click('case-inspect',secondReturn.id);await click('case-refund',secondReturn.id);await nav(orderPath);await delay();await check('multiple refunds in one shop remain independent','JSON.parse(localStorage.getItem("pcmatch-demo-v2")).orders[0].suborders.find(s=>s.shopId==="BP").refunds.length===2');
await nav(itemPath(ssd));await delay();await fill('case',{type:'warranty',qty:1,reason:'Kiểm tra ổ đĩa',text:'Nhờ shop kiểm tra lỗi demo.'});st=await state();const warranty=st.cases.find(c=>c.type==='warranty');await click('case-inspect',warranty.id);await click('case-sent',warranty.id);await click('case-replace',warranty.id);await click('case-received',warranty.id);await check('warranty replacement complete with serial','document.body.innerText.includes("Đã nhận lại sản phẩm")&&document.body.innerText.includes("Serial thay thế demo")');
await nav('buyer/cases.html?new=review&order='+order.id+'&sub='+bp.id+'&item='+ssd.id);await delay();await fill('review',{productRating:'4',shopRating:'3',text:'Sản phẩm tốt, dịch vụ cần cải thiện.'});await nav('buyer/cases.html?new=review&order='+order.id+'&sub='+bp.id+'&item='+ssd.id);await delay();await fill('review',{productRating:'5',shopRating:'4',text:'Shop đã hỗ trợ đổi sản phẩm.'});await check('one review updated with separate scores','JSON.parse(localStorage.getItem("pcmatch-demo-v2")).reviews.length===1&&JSON.parse(localStorage.getItem("pcmatch-demo-v2")).reviews[0].history.length===1');
await nav('buyer/cases.html?new=complaint&order='+order.id+'&sub='+bp.id+'&case='+warranty.id);await delay();await fill('case',{reason:'Cần giải thích chính sách',text:'Nhờ nền tảng xem lại phản hồi của shop.'});st=await state();const complaint=st.cases.find(c=>c.type==='complaint');await click('case-resolve',complaint.id);await check('transaction complaint distinct from report','document.body.innerText.includes("Đã xem xét khiếu nại")');
await nav('buyer/model.html?id=CPU-7600');await delay();await E('document.querySelector("a[href*=\\\"target=BP-CPU-7600\\\"]").click()');await delay();await fill('case',{reason:'Tin bán cần làm rõ',text:'Đề nghị kiểm tra thông tin mô tả offer.'});await check('offer report has target and no order','JSON.parse(localStorage.getItem("pcmatch-demo-v2")).cases.some(c=>c.type==="report"&&c.target==="BP-CPU-7600"&&!c.orderId)');
await nav('buyer/model.html?id=CPU-7600');await delay();await fill('question',{shopId:'BP',text:'Shop xác nhận giúp ngàm tản đi kèm?'});await check('presale question correct context','JSON.parse(localStorage.getItem("pcmatch-demo-v2")).questions[0].modelId==="CPU-7600"');
await nav('buyer/notifications.html');await delay();const nt=(await state()).notifications.find(n=>n.path.includes('cases'));await click('read-notification',nt.id);await check('notification opens exact case and marks read','location.href.includes('+JSON.stringify(nt.path.split('/').pop())+')&&JSON.parse(localStorage.getItem("pcmatch-demo-v2")).notifications.find(n=>n.id==='+JSON.stringify(nt.id)+').read');
// Keep a private draft/cart to prove account isolation and restoration.
await E(`(async()=>{const s=await import('/assets/js/store.js');s.tx(d=>d.draftBuild.name='Bản nháp riêng A');s.addItems([{offerId:'BP-PSU-750',qty:1}]);})()`);await nav('buyer/account.html');await delay();await click('logout');await E('history.back()');await delay();await check('logout then Back requires login','location.pathname.endsWith("login.html")');await nav('auth/login.html?mode=register');await delay();await fill('register',{name:'Người mua B',email:'after-b@test.local',password:'Demo12345',confirm:'Demo12345'});await check('second account has own profile and workspace','document.body.innerText.includes("Người mua B")&&JSON.parse(localStorage.getItem("pcmatch-demo-v2")).cart.length===0&&JSON.parse(localStorage.getItem("pcmatch-demo-v2")).draftBuild.name!=="Bản nháp riêng A"');
for(const path of [orderPath,'buyer/cases.html?id='+ret.id,'buyer/notifications.html']){await nav(path);await delay();await check('account B cannot read A '+path,'!document.body.innerText.includes("123 Đường Mẫu")&&!document.body.innerText.includes("proof.pdf")&&!document.querySelector("[data-action=read-notification]")');}
await click('logout');await nav('auth/login.html?mode=recover');await delay();await fill('recover',{email:'after-a@test.local'});await E('document.querySelector("a[href*=token]").click()');await delay();const resetURL=await E('location.href');await fill('password-reset',{password:'Recovered123',confirm:'Recovered123'});await fill('login',{email:'after-a@test.local',password:'Recovered123'});await check('recovery works and restores A workspace','JSON.parse(localStorage.getItem("pcmatch-demo-v2")).cart.length===1&&JSON.parse(localStorage.getItem("pcmatch-demo-v2")).draftBuild.name==="Bản nháp riêng A"');await E('location.href='+JSON.stringify(resetURL));await delay();await check('used reset link rejected','document.body.innerText.includes("Liên kết hết hạn hoặc đã dùng")');
for(const width of [360,768,1440]){await cdp('Emulation.setDeviceMetricsOverride',{width,height:1000,deviceScaleFactor:1,mobile:false});for(const path of [orderPath,'buyer/account.html','buyer/cases.html?id='+ret.id,'buyer/cases.html?id='+warranty.id,'buyer/notifications.html','buyer/help.html']){await nav(path);await delay();await check('responsive '+width+' '+path,'document.documentElement.scrollWidth<=innerWidth');}await nav(orderPath);await delay();fs.writeFileSync('/tmp/pcmatch-aftersale-'+width+'.png',Buffer.from((await cdp('Page.captureScreenshot',{format:'png'})).data,'base64'));}
console.log('AFTERSALE FLOWS PASSED');
