await cdp('Network.enable');await cdp('Network.setCacheDisabled',{cacheDisabled:true});await cdp('Network.setBlockedURLs',{urls:['*fonts.googleapis.com*','*fonts.gstatic.com*']});
const delay=async()=>{await new Promise(r=>setTimeout(r,600));for(let n=0;n<80;n++){const r=await ev('document.body.classList.contains("buyer-app")&&!document.querySelector("#main").innerText.includes("Đang tải")&&!document.querySelector("#main").innerText.includes("Đang xử lý thanh toán demo")');if(r.value)return;await new Promise(r=>setTimeout(r,150));}throw Error('Page did not finish loading')};
const E=async x=>{const r=await ev(x);if(r.subtype==='error')throw Error(r.description);return r.value;};
const check=async(label,x)=>{if(!await E(x))throw Error('FAIL '+label+' '+await E('document.body.innerText.slice(-1200)'));console.log('PASS',label)};
const fill=async(name,data)=>{await E('(()=>{const f=document.querySelector('+JSON.stringify('form[data-form="'+name+'"]')+');if(!f)throw Error("Missing form '+name+'");for(const [k,v] of Object.entries('+JSON.stringify(data)+')){const el=f.elements[k];if(!el)throw Error("Missing "+k);if(el.type==="checkbox")el.checked=v;else el.value=v;el.dispatchEvent(new Event("input",{bubbles:true}));}f.requestSubmit();})()');await delay();};
const click=async(action,id)=>{await E('document.querySelector('+JSON.stringify('[data-action="'+action+'"]'+(id?'[data-id="'+id+'"]':''))+').click()');await delay();};
const confirm=async()=>{await E('document.querySelector("#confirm button[value=ok]").click()');await delay();};
const state=async()=>JSON.parse(await E('localStorage.getItem("pcmatch-demo-v2")'));
await nav('buyer/home.html');await E('localStorage.clear();sessionStorage.clear()');await nav('buyer/home.html');await delay();
await E('document.querySelector("a[href*=builder]").click()');await delay();await check('eight slots','document.querySelectorAll("a[href*=slot]").length===8');
await E('document.querySelector("a[href*=\\\"slot=PSU\\\"]").click()');await delay();await check('PSU category context','[...document.querySelectorAll("[data-model-id]")].every(e=>e.dataset.modelId.startsWith("PSU-"))');
await E('document.querySelector("a[href*=\\\"model.html?id=PSU-750\\\"]").click()');await delay();await fill('offer',{qty:1,target:'build'});await check('correct PSU offer in slot','JSON.parse(localStorage.getItem("pcmatch-demo-v2")).draftBuild.slots.PSU.offerId==="BP-PSU-750"');
await fill('save-build',{name:'Máy làm việc'});await check('save requires login retaining build','location.pathname.endsWith("login.html")&&!!JSON.parse(localStorage.getItem("pcmatch-demo-v2")).draftBuild.slots.PSU');await E('document.querySelector("a[href*=register]").click()');await delay();await fill('register',{name:'Build tester',email:'build@test.local',password:'Demo12345',confirm:'Demo12345'});await fill('save-build',{name:'Máy làm việc'});
let st=await state(),bid=st.draftBuild.id;await nav('buyer/builds.html');await delay();await click('build-rename',bid);await E('document.querySelector("#confirm [name=name]").value="Máy đã đổi tên"');await confirm();await check('rename saved build','JSON.parse(localStorage.getItem("pcmatch-demo-v2")).builds[0].name==="Máy đã đổi tên"');await click('build-open',bid);
// Add a second slot while preserving PSU, then mark it owned beyond the offer stock.
let b=(await state()).draftBuild;await nav('buyer/model.html?id=RAM-K32&slot=RAM&build='+b.id+'&version='+b.version);await delay();await fill('offer',{qty:1,target:'build'});await check('other slots preserved','!!JSON.parse(localStorage.getItem("pcmatch-demo-v2")).draftBuild.slots.PSU');await fill('build-slot',{owned:true,qty:20});await check('owned quantity independent of shop stock','JSON.parse(localStorage.getItem("pcmatch-demo-v2")).draftBuild.slots.RAM.owned');
await click('build-cart');await confirm();await check('only needed offers in cart','JSON.parse(localStorage.getItem("pcmatch-demo-v2")).cart.length===1&&JSON.parse(localStorage.getItem("pcmatch-demo-v2")).cart[0].offerId==="BP-PSU-750"');
await nav('buyer/builder.html');await delay();await E('document.querySelector("a[href*=consultation]").click()');await delay();await fill('consult',{shopId:'BP',budget:30000000,text:'Kiểm tra nguồn và tư vấn case phù hợp.'});st=await state();const con=st.consultations[0];await check('consultation separate from proposals','location.pathname.endsWith("consultation.html")&&JSON.parse(localStorage.getItem("pcmatch-demo-v2")).proposals.length===0');await click('consult-reply',con.id);await check('response has version and price difference','document.body.innerText.includes("Chênh")&&document.body.innerText.includes("Đang tư vấn")');await click('consult-apply',con.id);await check('suggestion needs confirmation','!!document.querySelector("#confirm[open]")&&!JSON.parse(localStorage.getItem("pcmatch-demo-v2")).draftBuild.slots.CASE');await confirm();await check('apply and recompute','location.pathname.endsWith("builder.html")&&JSON.parse(localStorage.getItem("pcmatch-demo-v2")).draftBuild.slots.CASE.offerId==="BP-CASE-AIR"&&document.body.innerText.includes("Chưa đủ dữ liệu")&&document.body.innerText.includes("Có điều kiện")');await nav('buyer/consultation.html?id='+con.id);await delay();await click('consult-update',con.id);await check('consultation retains version history','JSON.parse(localStorage.getItem("pcmatch-demo-v2")).consultations[0].versions.length===2&&document.body.innerText.includes("Đồng ý áp dụng")');
await nav('buyer/home.html');await delay();await E('document.querySelector("a[href*=requests]").click()');await delay();await E('document.querySelector("a[href*=\\\"new=1\\\"]").click()');await delay();await fill('request',{purpose:'Máy lập trình',budget:-1,scope:'CPU, mainboard, RAM, GPU, SSD, PSU, case',owned:'Đã có màn hình',region:'HCM',assembly:true,status:'draft'});await check('invalid budget keeps draft','document.querySelector("[name=purpose]").value==="Máy lập trình"&&!document.querySelector("#confirm[open]")');await E('location.reload()');await delay();await check('draft restored after reload','document.querySelector("[name=purpose]").value==="Máy lập trình"');await fill('request',{budget:30000000});await confirm();st=await state();const req=st.requests[0];await check('draft request and no responses','document.body.innerText.includes("Bản nháp")&&document.body.innerText.includes("Chưa có phản hồi")');await nav('buyer/requests.html?id='+req.id+'&edit=1');await delay();await fill('request',{status:'open'});await confirm();await click('seed-proposals',req.id);st=await state();let p=st.proposals.find(p=>p.shopId==='BP');await nav('buyer/proposals.html?request='+req.id);await delay();await check('compare full proposals with item warranty','document.querySelectorAll(".proposal-line").length===14&&document.body.innerText.includes("BH 60 tháng")&&document.body.innerText.includes("Chênh ngân sách")');
await nav('buyer/proposals.html?id='+p.id);await delay();await E('sessionStorage.setItem("pcmatch-fail","1")');await fill('proposal-feedback',{text:'Giảm phí giao để phù hợp ngân sách.'});await check('feedback operation error preserves text','document.querySelector("[name=text]").value.includes("Giảm phí")&&document.body.innerText.includes("Lỗi thao tác")');await fill('proposal-feedback',{});await click('proposal-revise',p.id);st=await state();p=st.proposals.find(x=>x.previousId===p.id);await nav('buyer/proposals.html?id='+p.id);await delay();await check('new proposal version and difference','document.body.innerText.includes("Báo giá v2")&&document.body.innerText.includes("Chênh bản trước")');await fill('choose-proposal',{agree:true});await confirm();await check('selected proposal replaces cart with one shop','new Set(JSON.parse(localStorage.getItem("pcmatch-demo-v2")).cart.map(i=>i.offerId.split("-")[0])).size===1&&JSON.parse(localStorage.getItem("pcmatch-demo-v2")).cart.every(i=>i.offerId.startsWith("BP-"))');await nav('buyer/checkout.html');await delay();await nav('buyer/addresses.html?checkout=1');await delay();await fill('address',{name:'Build tester',phone:'0901234567',detail:'123 Đường Demo, Phường Demo',region:'HCM'});await check('revised fee retained in checkout','document.body.innerText.includes("15.000")&&JSON.parse(localStorage.getItem("pcmatch-demo-v2")).checkout.proposal.fee===15000');
for(const width of [360,768,1440]){await cdp('Emulation.setDeviceMetricsOverride',{width,height:1000,deviceScaleFactor:1,mobile:false});for(const path of ['builder','builds','consultation?id='+con.id,'requests?id='+req.id,'proposals?id='+p.id,'checkout']){const [r,q]=path.split('?');await nav('buyer/'+r+'.html'+(q?'?'+q:''));await delay();await check('responsive '+width+' '+r,'document.documentElement.scrollWidth<=innerWidth');}fs.writeFileSync('/tmp/pcmatch-build-checkout-'+width+'.png',Buffer.from((await cdp('Page.captureScreenshot',{format:'png'})).data,'base64'));}
await nav('buyer/model.html?id=SSD-MP44&shop=TZ');await delay();await fill('offer',{qty:1,target:'cart'});await check('mixing needs confirmation','!!document.querySelector("#confirm[open]")');await confirm();await check('mixed cart drops bundle promise','!JSON.parse(localStorage.getItem("pcmatch-demo-v2")).checkout.proposal&&document.body.innerText.includes("không còn áp dụng")');
// Pure compatibility regression: missing properties cannot accidentally pass undefined === undefined.
await check('missing specs never pass',`(async()=>{const {compatibility}=await import('/assets/js/builds.js');return compatibility({slots:{CPU:{offerId:'BP-PSU-750'},MB:{offerId:'BP-CASE-AIR'}}}).find(x=>x.title==='CPU và socket mainboard').state==='Chưa đủ dữ liệu'})()`);
let edgeState=await state(),saved=edgeState.builds[0];await nav('buyer/builds.html');await delay();await click('build-share',saved.id);saved=(await state()).builds[0];await nav('buyer/builder.html?share='+saved.share);await delay();await check('shared build read only','!document.querySelector("form[data-form=build-slot]")&&!document.querySelector("[data-action=build-cart]")');await nav('buyer/builds.html');await delay();await click('build-share',saved.id);await nav('buyer/builder.html?share='+saved.share);await delay();await check('revoked share inaccessible','document.body.innerText.includes("Liên kết không còn hiệu lực")');await nav('buyer/builds.html');await delay();await click('build-delete',saved.id);await E('document.querySelector("#confirm [value=cancel]").click()');await check('cancel delete keeps saved build','JSON.parse(localStorage.getItem("pcmatch-demo-v2")).builds.length===1');await click('build-delete',saved.id);await confirm();await check('delete saved build','JSON.parse(localStorage.getItem("pcmatch-demo-v2")).builds.length===0');
await nav('buyer/builder.html');await delay();let edgeBuild=(await state()).draftBuild;await nav('buyer/model.html?id=PSU-550&slot=PSU&build='+edgeBuild.id+'&version='+edgeBuild.version);await delay();await fill('offer',{qty:1,target:'build'});await check('replace slot asks confirmation','!!document.querySelector("#confirm[open]")');await confirm();await check('replace PSU preserves RAM and case','JSON.parse(localStorage.getItem("pcmatch-demo-v2")).draftBuild.slots.PSU.offerId==="BP-PSU-550"&&!!JSON.parse(localStorage.getItem("pcmatch-demo-v2")).draftBuild.slots.RAM&&!!JSON.parse(localStorage.getItem("pcmatch-demo-v2")).draftBuild.slots.CASE');await click('slot-delete','RAM');await check('delete one slot preserves others','!JSON.parse(localStorage.getItem("pcmatch-demo-v2")).draftBuild.slots.RAM&&!!JSON.parse(localStorage.getItem("pcmatch-demo-v2")).draftBuild.slots.PSU');
const cid=(await state()).consultations[0].id;await nav('buyer/consultation.html?id='+cid);await delay();await click('consult-reply',cid);await click('consult-apply',cid);await check('stale consultation cannot overwrite build','document.body.innerText.includes("Phản hồi thuộc cấu hình cũ")&&!document.querySelector("#confirm[open]")');
console.log('BUILD EDGE FLOWS PASSED');

// Complete both supplemental purchase branches through payment, using the existing address.
await nav('buyer/cart.html');await delay();await click('cart-remove');await confirm();
await nav('buyer/builder.html');await delay();await click('build-cart');await confirm();await nav('buyer/checkout.html');await delay();await fill('place-order',{changes:true,terms:true});await fill('pay',{result:'paid'});await check('self build reaches paid order','document.body.innerText.includes("Thanh toán demo thành công")');
await nav('buyer/requests.html?new=1');await delay();await fill('request',{purpose:'Cấu hình đặt trọn bộ',budget:30000000,owned:'Không',region:'HCM',status:'open'});await confirm();const finalReq=(await state()).requests.at(-1);await click('seed-proposals',finalReq.id);const finalProposal=(await state()).proposals.find(p=>p.requestId===finalReq.id&&p.shopId==='TZ');await nav('buyer/proposals.html?id='+finalProposal.id);await delay();await fill('choose-proposal',{agree:true});await confirm();await nav('buyer/checkout.html');await delay();await fill('place-order',{changes:true,terms:true});await fill('pay',{result:'paid'});await check('budget proposal reaches correct paid shop order','JSON.parse(localStorage.getItem("pcmatch-demo-v2")).orders.at(-1).suborders.length===1&&JSON.parse(localStorage.getItem("pcmatch-demo-v2")).orders.at(-1).suborders[0].shopId==="TZ"&&JSON.parse(localStorage.getItem("pcmatch-demo-v2")).orders.at(-1).payment==="paid"');
console.log('BUILD FLOWS PASSED');
