await cdp('Network.enable');await cdp('Network.setCacheDisabled',{cacheDisabled:true});await cdp('Network.setBlockedURLs',{urls:['*fonts.googleapis.com*','*fonts.gstatic.com*']});
const delay=async()=>{await new Promise(r=>setTimeout(r,600));for(let n=0;n<80;n++){const r=await ev('document.body.classList.contains("buyer-app")&&!document.querySelector("#main").innerText.includes("Đang tải")&&!document.querySelector("#main").innerText.includes("Đang xử lý thanh toán demo")');if(r.value)return;await new Promise(r=>setTimeout(r,150));}throw Error('Page did not finish loading')};
const E=async x=>{const r=await ev(x);if(r.subtype==='error')throw Error(r.description);return r.value;};
const check=async(label,x)=>{if(!await E(x))throw Error('FAIL '+label+' '+await E('document.body.innerText.slice(-1200)'));console.log('PASS',label)};
const fill=async(name,data)=>{await E('(()=>{const f=document.querySelector('+JSON.stringify('form[data-form="'+name+'"]')+');if(!f)throw Error("Missing form '+name+'");for(const [k,v] of Object.entries('+JSON.stringify(data)+')){const el=f.elements[k];if(!el)throw Error("Missing "+k);if(el.type==="checkbox")el.checked=v;else el.value=v;el.dispatchEvent(new Event("input",{bubbles:true}));}f.requestSubmit();})()');await delay();};
const click=async(action,id)=>{await E('document.querySelector('+JSON.stringify('[data-action="'+action+'"]'+(id?'[data-id="'+id+'"]':''))+').click()');await delay();};
const confirm=async()=>{await E('document.querySelector("#confirm button[value=ok]").click()');await delay();};
const state=async()=>JSON.parse(await E('localStorage.getItem("pcmatch-demo-v2")'));
await nav('buyer/home.html');await E('localStorage.clear();sessionStorage.clear()');await nav('buyer/cart.html');await delay();
await check('empty cart with shopping route','document.body.innerText.includes("Giỏ hàng đang trống")&&!!document.querySelector("a[href*=search]")');
await nav('buyer/home.html');await delay();await E('document.querySelector("a[href*=\\\"model.html\\\"]").click()');await delay();
await fill('offer',{qty:1,target:'cart'});let st=await state();const offer=st.cart[0].offerId;
await check('home → model → exact offer → cart','location.pathname.endsWith("cart.html")&&document.body.innerText.includes('+JSON.stringify(offer)+')');
await fill('cart-qty',{qty:-1});await check('negative qty rejected beside field','!!document.querySelector("[name=qty][aria-invalid=true]")&&JSON.parse(localStorage.getItem("pcmatch-demo-v2")).cart[0].qty===1');
await fill('cart-qty',{qty:1.5});await check('fraction qty rejected','JSON.parse(localStorage.getItem("pcmatch-demo-v2")).cart[0].qty===1');
await fill('cart-qty',{qty:1});await click('qty-up');await check('increment applied','JSON.parse(localStorage.getItem("pcmatch-demo-v2")).cart[0].qty===2');await click('qty-down');
await nav('buyer/checkout.html');await delay();await fill('login',{email:'',password:''});await check('empty login blocked','location.pathname.endsWith("login.html")&&!!document.querySelector(".field-error")');await fill('login',{email:'wrong@test.local',password:'wrong'});await check('wrong login blocked with field error','!!document.querySelector("[name=password][aria-invalid=true]")');
await E('document.querySelector("a[href*=register]").click()');await delay();await fill('register',{name:'Mua hàng demo',email:'purchase@test.local',password:'Demo12345',confirm:'Mismatch123'});await check('password confirmation at field','!!document.querySelector("[name=confirm][aria-invalid=true]")');await fill('register',{confirm:'Demo12345'});
await check('register returns checkout and preserves guest cart','location.pathname.endsWith("checkout.html")&&JSON.parse(localStorage.getItem("pcmatch-demo-v2")).cart[0].offerId==='+JSON.stringify(offer));
await click('logout');await nav('buyer/checkout.html');await delay();await fill('login',{email:'purchase@test.local',password:'Demo12345'});await check('login returns to checkout with same offer','location.pathname.endsWith("checkout.html")&&JSON.parse(localStorage.getItem("pcmatch-demo-v2")).cart[0].offerId==='+JSON.stringify(offer));
await nav('buyer/addresses.html?checkout=1');await delay();await fill('address',{name:' ',phone:'123',detail:'short'});await check('bad address blocked','location.pathname.endsWith("addresses.html")&&!!document.querySelector(".field-error")');await fill('address',{name:'Người mua',phone:'0901234567',detail:'123 Đường Demo, Phường Demo',region:'HCM'});
await fill('voucher',{code:'EXPIRED'});await check('expired voucher preserves checkout','document.body.innerText.includes("Voucher đã hết hạn")&&location.pathname.endsWith("checkout.html")');
await click('price-change');await check('old/new price shown and consent unchecked','document.body.innerText.includes("Thay đổi giá cần xác nhận")&&!document.querySelector("[name=changes]").checked');
await fill('place-order',{changes:false,terms:false});await check('unchecked consent cannot order','JSON.parse(localStorage.getItem("pcmatch-demo-v2")).orders.length===0');
await click('shipping-error');await fill('place-order',{changes:true,terms:true});await check('shipping error blocks order','JSON.parse(localStorage.getItem("pcmatch-demo-v2")).orders.length===0');await click('shipping-retry');
// Exact document arithmetic fixture, isolated to this browser profile.
await E(`(async()=>{const s=await import('/assets/js/store.js');s.tx(d=>{d.cart=[{id:'CI-FEE',offerId:'BP-CPU-7600',qty:1,price:20030000,stock:8}];d.overrides={'BP-CPU-7600':{price:20030000}};d.checkout={services:{BP:'fast'}};});location.reload();})()`);await delay();
await check('fee fixture 20,150,000','document.querySelector("[data-total]").textContent.replace(/[^0-9]/g,"")==="20150000"');await fill('delivery',{service:'standard'});await check('fee reduced 120k → 65k, total 20,095,000','document.querySelector("[data-total]").textContent.replace(/[^0-9]/g,"")==="20095000"&&document.body.innerText.includes("Thay đổi phí giao cần xác nhận")');
for(const width of [360,1440]){await cdp('Emulation.setDeviceMetricsOverride',{width,height:1000,deviceScaleFactor:1,mobile:false});await check('checkout fee review fits '+width,'document.documentElement.scrollWidth<=innerWidth');fs.writeFileSync('/tmp/pcmatch-checkout-'+width+'.png',Buffer.from((await cdp('Page.captureScreenshot',{format:'png',captureBeyondViewport:true})).data,'base64'));}
await E(`(()=>{const f=document.querySelector('form[data-form=place-order]');f.elements.changes.checked=true;f.elements.terms.checked=true;f.requestSubmit();f.requestSubmit();})()`);await delay();await check('double submit creates one order','location.pathname.endsWith("payment.html")&&JSON.parse(localStorage.getItem("pcmatch-demo-v2")).orders.length===1');
await fill('pay',{result:'failed'});await check('failed payment offers retry','document.body.innerText.includes("Thử thanh toán lại")');await fill('pay',{result:'unknown'});await check('unknown payment offers check','!!document.querySelector("[data-action=payment-check]")');await click('payment-check');
await E(`(()=>{const f=document.querySelector('form[data-form=pay]');f.elements.result.value='paid';f.requestSubmit();})()`);await new Promise(r=>setTimeout(r,350));await check('processing payment visible','document.body.innerText.includes("Đang xử lý thanh toán demo")');await delay();await check('success result for new order','document.body.innerText.includes("Thanh toán demo thành công")');
st=await state();const order=st.orders[0];await E('document.querySelector("a[href*=\\\"order.html\\\"]").click()');await delay();await check('correct order pending shop, never delivered','location.search.includes('+JSON.stringify(order.id)+')&&document.body.innerText.includes("Chờ shop xác nhận")&&!document.body.innerText.includes("Giao nhận: Đã giao")');
await nav('buyer/addresses.html');await delay();let addressId=(await state()).addresses[0].id;await nav('buyer/addresses.html?edit='+addressId);await delay();await fill('address',{name:'Người nhận đã sửa',phone:'0912345678',detail:'456 Đường Mới, Phường Demo',region:'HN'});await check('address edit preserves order snapshot','JSON.parse(localStorage.getItem("pcmatch-demo-v2")).orders[0].address.name==="Người mua"');await click('address-delete',addressId);await E('document.querySelector("#confirm [value=cancel]").click()');await check('cancel address deletion keeps address','JSON.parse(localStorage.getItem("pcmatch-demo-v2")).addresses.length===1');await click('address-delete',addressId);await confirm();await check('confirmed delete keeps historical address','JSON.parse(localStorage.getItem("pcmatch-demo-v2")).addresses.length===0&&JSON.parse(localStorage.getItem("pcmatch-demo-v2")).orders[0].address.name==="Người mua"');
await nav('buyer/orders.html');await delay();await fill('order-filter',{q:order.id,status:'paid'});await check('order search opens correct id','!!document.querySelector("a[href*=\\\"'+order.id+'\\\"]")');
for(const width of [360,768,1440]){await cdp('Emulation.setDeviceMetricsOverride',{width,height:1000,deviceScaleFactor:1,mobile:false});for(const p of ['cart','checkout','payment?id='+order.id,'order?id='+order.id,'addresses','orders']){const [r,q]=p.split('?');await nav('buyer/'+r+'.html'+(q?'?'+q:''));await delay();await check('responsive '+width+' '+r,'document.documentElement.scrollWidth<=innerWidth');}fs.writeFileSync('/tmp/pcmatch-purchase-'+width+'.png',Buffer.from((await cdp('Page.captureScreenshot',{format:'png'})).data,'base64'));}
await E(`(async()=>{const s=await import('/assets/js/store.js');s.tx(d=>{d.orders[0].payment='pending';d.orders[0].expires=Date.now()-1;});})()`);await nav('buyer/payment.html?id='+order.id);await delay();await check('expired payment cannot pay','document.body.innerText.includes("Phiên thanh toán hết hạn")&&!document.querySelector("form[data-form=pay]")');
console.log('PURCHASE FLOWS PASSED');
